version: '3'
services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "..:/workspace"
      - "~/.gitignore:/root/.gitignore"
      - "~/.gitconfig:/root/.gitconfig"
      - "~/.ssh:/root/.ssh"
    env_file: ../.env
    command: sleep infinity
    ports:
      - '8888:8888'
      - '8889:8889'