version: '3'
services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "..:/workspace"
      - "../configs/.databrickscfg:/root/.databrickscfg"
      - "../configs/.jupyter:/root/.jupyter"
      - "~/.gitconfig:/root/.gitconfig"
      - "~/.gitignore:/root/.gitignore"
      - "~/.ssh:/root/.ssh"
    env_file: ../configs/.env
    ports:
      - "127.0.0.1:8888:8888"
    command: sleep infinity
