version: '3'
services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "..:/workspace"
      - "../configs/.databrickscfg:/home/alex/.databrickscfg"
      - "../configs/.jupyter:/home/alex/.jupyter"
      - "~/.gitconfig:/home/alex/.gitconfig"
      - "~/.gitignore:/home/alex/.gitignore"
      - "~/.ssh:/home/alex/.ssh"
    env_file: ../configs/.env
    ports:
      - "127.0.0.1:8888:8888"
    command: sleep infinity
