version: '3'
services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "..:/workspace"
      - "~/.gitignore:/root/.gitignore"
      - "~/.gitconfig:/root/.gitconfig"
      - "~/.ssh:/root/.ssh"
    env_file: ../.env
    command: sleep infinity
  jupyter:
    image: jupyter/pyspark-notebook:latest
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - "../.jupyter:/home/jovyan/.jupyter"
      - "..:/home/jovyan/work"