version: '3'
services:
  workspace:
    build:
      context: .
      dockerfile: workspace.Dockerfile
    volumes:
      - "..:/workspace"
      - "~/.ssh:/root/.ssh"
      - "~/.gitignore:/root/.gitignore"
      - "~/.gitconfig:/root/.gitconfig"
    env_file: ../.env
    command: sleep infinity
  jupyter:
    build:
      context: .
      dockerfile: jupyter.Dockerfile
    ports:
      - "127.0.0.1:8888:8888"
    env_file: ../.env
    volumes:
      - "..:/workspace"
      - "~/.ssh:/root/.ssh"
      - "../.jupyter:/root/.jupyter"
      - "../.databrickscfg:/root/.databrickscfg"